#:schema node_modules/wrangler/config-schema.json
name = "embed"
main = "../../.worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = "../../.worker-next/assets", binding = "ASSETS" }

routes = [{ pattern = "embed.fit", custom_domain = true }]

[vars]
BASE_URL = "embed.fit"
TURNSTILE_SITE_KEY = "0x4AAAAAAAy4-xm9WOhO5RmW"

[[kv_namespaces]]
binding = "kvcache"
id = "7f87b2ba5c2344b6b7f14e1f96c3189b"
